---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infrastore-media-pvc
  namespace: infrastore
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infrastore-db-pvc
  namespace: infrastore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard